/// The immutable, shareable description of a board. A board is NEVER persisted
/// as cells over the wire — only as this spec, then regenerated by re-running
/// the deterministic generator. Fold exactly these five fields into the PRNG
/// seed so identical specs yield identical boards (ARCHITECTURE.md §8).
library;

enum WinMode { fullBoard, lines }

class BoardSpec {
  final String seed;
  final int size; // 3 | 4 | 5
  final bool freeSpace; // centre auto-marked on odd sizes
  final String catalogVersion; // freezes WHICH item universe the pool comes from
  final int algoVersion; // versioned generator dispatch
  final String configHash; // snapshot of quotas/weights/caps/winModes
  final List<WinMode> winModes;
  final String mode; // "solo" | "async" | "realtime" — label only

  const BoardSpec({
    required this.seed,
    required this.size,
    required this.catalogVersion,
    required this.algoVersion,
    required this.configHash,
    this.freeSpace = true,
    this.winModes = const [WinMode.fullBoard],
    this.mode = 'solo',
  });

  int get cellCount => size * size;

  bool get hasFreeCenter => freeSpace && size.isOdd;

  /// Index of the auto-marked free centre, or null on even sizes.
  int? get freeIndex => hasFreeCenter ? (cellCount ~/ 2) : null;

  /// Number of catalog items to place (cells minus the free centre).
  int get pickCount => cellCount - (hasFreeCenter ? 1 : 0);

  /// The exact, ordered material folded into the PRNG seed. Changing any field
  /// changes every draw; `algoVersion` also dispatches the generator so a new
  /// algorithm never breaks an already-shared board.
  String get seedMaterial =>
      [seed, '$size', catalogVersion, '$algoVersion', configHash].join('|');
}
